<?php

//AQUI EU TENHO QUE PEGAR A FOTO DA PESSOA QUE TÁ LOGADA, O NOME, E CADASTRAR NO BANCO
//DEPOIS NOS COMENTARIOS.PHP TENHO Q PEGAR TUDO E POR DENTRO DA DIV E NA RESPECTIVA NOTICIA
    $comentario = $_POST['comentario'];

    echo "<h1> $comentario </h1>";
?>